FROM golang:alpine as builder

WORKDIR /build
COPY . .

ARG GOARCH="arm"
ARG GOARM="7"
RUN go get -u ./... && \
   GOOS=linux GOARCH=$GOARCH GOARM=$GOARM go build -ldflags="-w -s" -o build

FROM arm32v7/alpine:latest

WORKDIR /build
COPY --from=builder /build/build .

ENV SCYTHER_CONNECTION ""
ENTRYPOINT ./build
