package storage

const (
	TABLE_QUEUES = "queues"
	TABLE_ITEMS  = "items"

	FIELDS_QUEUES = "id, name, capacity, size"
	FIELDS_ITEMS  = "id, queue, data"

	SCHEMA_QUEUES = `
	        id CHAR(36) UNIQUE PRIMARY KEY NOT NULL,
	        name CHAR(255) UNIQUE,
	        capacity BIGINT UNSIGNED,
	        size BIGINT UNSIGNED NOT NULL,
	        ordered BIGINT UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT`
	SCHEMA_ITEMS = `
			id CHAR(36) UNIQUE PRIMARY KEY NOT NULL,
			queue CHAR(36) NOT NULL,
			data BINARY(255) NOT NULL,
			ordered BIGINT UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT`

	CREATE_TABLE_QUEUES = "CREATE TABLE IF NOT EXISTS " + TABLE_QUEUES + " (" + SCHEMA_QUEUES + ")"
	CREATE_TABLE_ITEMS  = "CREATE TABLE IF NOT EXISTS " + TABLE_ITEMS + " (" + SCHEMA_ITEMS + ")"

	COUNT_QUEUES     = "SELECT count(*) FROM " + TABLE_QUEUES
	READ_MANY_QUEUES = "SELECT " + FIELDS_QUEUES + " FROM " + TABLE_QUEUES + " ORDER BY ordered"
	WRITE_QUEUE      = "INSERT INTO " + TABLE_QUEUES + "(" + FIELDS_QUEUES + ") VALUES (?, ?, ?, 0)"
)
